### PR TITLE
FZ10RO-47__user

### PR DESCRIPTION
**Pull request by mateusziwanczuk**

### CODE REVIEW

**Comment by mateusziwanczuk** [comment]
I need this console.log to work with json data :)

**Comment by mateusziwanczuk** [comment]
Console.log deleted. Thank you!
Yep, this warning is concern dashboard section.

**Comment by joanna-by** [comment]
There is still one console.log. Should it be there?
No warnings though.

**Comment by mateusziwanczuk** [comment]
@joanna-by Remember to pull my branch, there are no more console.logs :)

**Comment by mateusziwanczuk** [comment]
New commit - I changed app name to Pizzerium in index.html.

**Comment by mateusziwanczuk** [comment]
Yep, I'm workin' on it.

**Pull request merged**
